# Generated by Django 3.2 on 2021-04-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cheese',
            field=models.CharField(choices=[('10 Ounces', '0'), ('8 Ounces', '1'), ('6 Ounces', '2'), ('3 Ounces', '3'), ('2 Ounces', '4')], default='10 Ounces', max_length=30),
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
