# Generated by Django 3.2 on 2021-04-10 02:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210409_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cheese',
            field=models.CharField(choices=[('10 Ounces', '10 Ounces'), ('8 Ounces', '8 Ounces'), ('6 Ounces', '6 Ounces'), ('3 Ounces', '3 Ounces'), ('2 Ounces', '2 Ounces')], default='10 Ounces', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='no_of_pizza',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.CharField(choices=[('Small-8/20 cm', 'Small-8/20 cm'), ('Medium-10/25 cm', 'Medium-10/25 cm'), ('Large-12/30 cm', 'Large-12/30 cm'), ('X-Large-16/40 cm', 'X-Large-16/40 cm'), ('Italian-12/30 cm', 'Italian-12/30 cm'), ('Large-14/35 cm', 'Large-14/35 cm'), ('Family XXL-16/40cm', 'Family XXL-16/40cm')], default='Small-8"/20 cm', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_type',
            field=models.CharField(choices=[('Margherita', 'Margherita'), ('Double Cheese Margherita', 'Double Cheese Margherita'), ('Farm House', 'Farm House'), ('Peppy Paneer', 'Peppy Paneer'), ('Mexican Green Wave', 'Mexican Green Wave'), ('Deluxe Veggie', 'Deluxe Veggie'), ('Veg Extravaganza', 'Veg Extravaganza'), ('Cheese N Corn', 'Cheese N Corn'), ('Paneer Makhni', 'Paneer Makhni'), ('Veggi Paradise', 'Veggi Paradise'), ('Fresh Veggie', 'Fresh Veggie'), ('Indi Tandoori Paneer', 'Indi Tandoori Paneer'), ('Chicken Golden Delight', 'Chicken Golden Delight'), ('Non Veg Supreme', 'Non Veg Supreme')], default='Margherita', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('black_olives', 'Black Olives'), ('crisp_capsicum', 'Crisp Capsicum'), ('paneer', 'Paneer'), ('mushroom', 'Mushroom'), ('golden_corn', 'Golden Corn'), ('fresh_tomato', 'Fresh Tomato'), ('jalapeno', 'Jalapeno'), ('red_pepper', 'Red Pepper'), ('babycorn', 'Baby Corn'), ('italian_sausage', 'Italian Sausage'), ('italian_style_pork_topping', 'Italian Style Pork Topping'), ('pork_topping', 'Pork Topping'), ('beef_topping', 'Beef Topping'), ('sliced_pork_roll', 'Sliced Pork Roll'), ('quartered_ham', 'Quartered Ham'), ('bacon', 'Bacon')], max_length=203),
        ),
    ]
